### PR TITLE
Code reformatting

### PR DESCRIPTION
**Pull request by ilessiivi**
Tried to make the code prettier and similar across the different files. I made some possibly controversial choices such as using tabs instead of spaces and " instead of ' so let me know if those are an issue.

There's also 32px and 64px sprites for the 151 first pokemon and a custom marker (`pokemonIcon(num)`) that can display them on the map.

### CODE REVIEW

**Comment by bettse** [comment]
I'm very much on the 'spaces' side of the spaces-vs-tabes debate, so if you can reformat to use spaces for indentation, that would make me much happier.  This is, in many ways, my own fault for not having an editorconfig file or something written up about coding guidelines.  Its good that we get the issues solved early.  I'll take it on as a task to do something about it.  

As for your other changes, could you post a screenshot of the ui so we can see how some of the new CSS rules impact it?

Other than the tabs, I think it looks good to go.

**Comment by pock2793** [comment]
im curious why bother resizing the pokemon icons when we can just do that with the markers? it makes more sense to keep them 128x128 incase we need to use the bigger size

**Comment by bettse** [comment]
I think its the data size consideration.  If it only downloads the larger images when it needs to.  If file size were linear to image size, and image (pixel) size is square the height (square images), then it would be a 4:1 ration of data savings for non-retina devices.  

That being said, I'm OK either way 👿

**Comment by pock2793** [comment]
only reason i was saying that is cause during testing i found 32x32 to be too small and 64x64 to be a bit too big

**Comment by bettse** [comment]
I think this calls for a battle of screenshots!

**Comment by ilessiivi** [comment]
Using correctly sized image (larger images for high resolution displays) is a good practice in general, that improves the load times on slower network connections. At 32 or 48 or 128 pixels the data savings are insignificant but hey, being a responsible coder is important. The drawback is of course that it makes it a bit more difficult to change the sizes later as the images will have to be scaled again but that can be scripted.

Here's some comparison screenshots.

New:
mapui_new

Versus old:
mapui_old

New with 48 pixel Pokemon sprites instead of 32:
mapui_new_48pokes

**Comment by ilessiivi** [comment]
The tabs are now changed to 2 spaces.

**Comment by SwissKid** [comment]
Rebase please

**Comment by ilessiivi** [comment]
Done - should be up to date now.

**Comment by bettse** [comment]
👍

**Pull request merged**
