### PR TITLE
Live update current population queue status

### PR DESCRIPTION
**Pull request by ilessiivi**
Fetches the queue length from server after either of the populate buttons are pressed.

shot

### CODE REVIEW

**Comment by SwissKid** [comment]
What's the benefit? they can see if the queue is going down, but they have no clue where their request is in the queue.

**Comment by ilessiivi** [comment]
It'll show the user's original place in the queue, and then they could watch the counter count down if there are no more requests after theirs. I think this is a simple way of improving the user experience of populating the data which in it's current form is uninformative ("wait 30 seconds and maybe something has happened"). If the counter is at zero their data would be guaranteed to be there.

This would be an increase on the server load though, depending on how optimized the query for the queue count is...

**Comment by SwissKid** [comment]
The queue count isn't bad (return q.qsize() in a python flask app).

However, the load is horrendous already, so I don't want to add this yet. Maybe in the future.

**Comment by ilessiivi** [comment]
Alright, I'll close this PR for now but leave the branch there for the future.

**Pull request closed without merging**
